import { test, expect } from '@playwright/test'
test('registro, persistencia, edición, filtros, exportación y eliminación',async({page})=>{
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'Tu glucosa, a tu ritmo.'})).toBeVisible()
  await page.getByLabel('¿Qué valor marcó tu glucómetro?').fill('105')
  await page.getByRole('button',{name:'Sí, en ayunas',exact:true}).click()
  await page.getByRole('button',{name:'Guardar medición',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Medición guardada')
  await page.reload()
  await expect(page.getByRole('button',{name:'Editar medición de 105'})).toBeVisible()
  await page.getByRole('button',{name:'Editar medición de 105'}).click()
  await page.getByRole('dialog').getByLabel('¿Qué valor marcó tu glucómetro?').fill('112')
  await page.getByRole('button',{name:'Guardar cambios'}).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.getByRole('button',{name:'Mis mediciones',exact:true}).click()
  await page.getByLabel('Momento').selectOption('no')
  await expect(page.getByText('0 registros',{exact:true})).toBeVisible()
  await page.getByLabel('Momento').selectOption('yes')
  await expect(page.getByText('1 registros',{exact:true})).toBeVisible()
  const downloadPromise=page.waitForEvent('download')
  await page.getByRole('button',{name:'Exportar CSV'}).click()
  const download=await downloadPromise
  expect(download.suggestedFilename()).toMatch(/salud100-.*\.csv/)
  const stream=await download.createReadStream();const chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(chunk)
  const csv=Buffer.concat(chunks).toString('utf8');expect(csv).toContain('112');expect(csv).toContain('En ayunas')
  await page.getByRole('button',{name:'Eliminar medición de 112'}).click()
  await page.getByRole('dialog').getByRole('button',{name:'Eliminar medición',exact:true}).click()
  await page.reload()
  await expect(page.getByRole('button',{name:/Editar medición/})).toHaveCount(0)
})
test('rechaza valores inválidos, conserva unidad y fecha, y funciona sin red',async({page,context})=>{
  await page.goto('/')
  await page.getByLabel('¿Qué valor marcó tu glucómetro?').fill('-5')
  await page.getByRole('button',{name:'Guardar medición',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('mayor que 0')
  await page.getByRole('button',{name:'Ajustes',exact:true}).click()
  await page.getByLabel('Unidad de nuevas mediciones').selectOption('mmol/L')
  await page.getByRole('button',{name:'Mi resumen',exact:true}).click()
  await context.setOffline(true)
  await page.getByLabel('¿Qué valor marcó tu glucómetro?').fill('5,8')
  await page.getByRole('button',{name:'Cambiar',exact:true}).click()
  await page.getByLabel('Fecha y hora de la medición',{exact:true}).fill('2025-08-15T08:30')
  await page.getByRole('button',{name:'Guardar medición',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Medición guardada')
  const records=await page.evaluate(()=>JSON.parse(localStorage.getItem('salud100.readings.v1')!))
  expect(records[0].value).toBe(5.8);expect(records[0].unit).toBe('mmol/L');expect(records[0].fasting).toBeNull()
  expect(new Date(records[0].measured_at).getTime()).toBeGreaterThan(0)
})
test('no sobrescribe datos dañados y no desborda el ancho de pantalla',async({page})=>{
  await page.addInitScript(()=>localStorage.setItem('salud100.readings.v1','broken'))
  await page.goto('/')
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.getByRole('button',{name:'Guardar medición',exact:true})).toBeDisabled()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
})
test('PWA recarga sin red después de instalar el service worker',async({page,context})=>{
  await page.goto('/')
  await page.evaluate(async()=>{await navigator.serviceWorker.ready})
  await page.reload()
  await expect(page.getByRole('heading',{name:'Tu glucosa, a tu ritmo.'})).toBeVisible()
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading',{name:'Tu glucosa, a tu ritmo.'})).toBeVisible()
  await page.getByLabel('¿Qué valor marcó tu glucómetro?').fill('98')
  await page.getByRole('button',{name:'Guardar medición',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Medición guardada')
  await page.reload()
  await expect(page.getByRole('button',{name:'Editar medición de 98'})).toBeVisible()
})
