import { test, expect } from '@playwright/test'

test('presión: validación, persistencia, resumen, edición, CSV y eliminación', async ({ page, context }) => {
  await page.goto('/')
  await page.getByLabel('¿Qué valor marcó tu glucómetro?').fill('105')
  await page.getByRole('button', { name: 'Guardar medición', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Medición guardada')
  await page.getByRole('button', { name: 'Presión arterial', exact: true }).click()
  await expect(page.getByText('¿Estabas en ayunas?')).toHaveCount(0)
  await context.setOffline(true)
  await page.getByLabel('Sistólica (mmHg)', { exact: true }).fill('120')
  await page.getByRole('button', { name: 'Guardar medición', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('números enteros')
  await page.getByLabel('Diastólica (mmHg)', { exact: true }).fill('130')
  await page.getByRole('button', { name: 'Guardar medición', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('mayor que la diastólica')
  await page.getByLabel('Diastólica (mmHg)', { exact: true }).fill('80')
  await page.getByRole('button', { name: 'Guardar medición', exact: true }).click()
  await expect(page.locator('.latest-value')).toContainText('120/80')
  await page.getByLabel('Sistólica (mmHg)', { exact: true }).fill('130')
  await page.getByLabel('Diastólica (mmHg)', { exact: true }).fill('90')
  await page.getByRole('button', { name: 'Guardar medición', exact: true }).click()
  await expect(page.locator('.weekly-stats')).toContainText('125/85')
  await expect(page.getByRole('img', { name: /Gráfica de 2 mediciones en mmHg/ })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.screenshot({ path: test.info().outputPath('pressure.png'), fullPage: true })
  await context.setOffline(false)
  await page.reload()
  await page.getByRole('button', { name: 'Editar medición de 120/80', exact: true }).click()
  await page.getByRole('dialog').getByLabel('Diastólica (mmHg)', { exact: true }).fill('82')
  await page.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.getByRole('button', { name: 'Mis mediciones', exact: true }).click()
  await page.getByRole('combobox', { name: 'Tipo', exact: true }).selectOption('pressure')
  await expect(page.getByText('2 registros', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Momento')).toBeDisabled()
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Exportar CSV' }).click()
  const download = await pending
  const stream = await download.createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(chunk)
  const csv = Buffer.concat(chunks).toString('utf8')
  expect(csv).toContain('Sistólica')
  expect(csv).toContain('"120","82","mmHg"')
  await page.getByRole('button', { name: 'Eliminar medición de 120/82', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('120/82 mmHg')
  await page.getByRole('dialog').getByRole('button', { name: 'Eliminar medición', exact: true }).click()
  await expect(page.getByText('1 registros', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Editar medición de 120/82', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Editar medición de 105', exact: true })).toBeVisible()
})

test('conserva registros locales de glucosa anteriores a la actualización', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('salud100.readings.v1', JSON.stringify([
    { id: 'legacy', value: 99, unit: 'mg/dL', measured_at: new Date().toISOString(), fasting: true, note: 'Anterior' },
  ])))
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Editar medición de 99', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Presión arterial', exact: true }).click()
  await page.getByLabel('Sistólica (mmHg)', { exact: true }).fill('120')
  await page.getByLabel('Diastólica (mmHg)', { exact: true }).fill('80')
  await page.getByRole('button', { name: 'Guardar medición', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Editar medición de 120/80', exact: true })).toBeVisible()
  const records = await page.evaluate(() => JSON.parse(localStorage.getItem('salud100.readings.v1')!))
  expect(records).toHaveLength(2)
  expect(records.find((r: { id: string }) => r.id === 'legacy').value).toBe(99)
})
