import { AuthScreen } from './components/AuthScreen'
import { authErrorMessage, readAuthRedirectError } from './lib/auth-feedback'
import { useEffect, useRef, useState, type FormEvent } from 'react'
import { Activity, ArrowDownToLine, ArrowRight, Check, ChevronRight, Clock3, Coffee, Droplet, Heart, History, LayoutDashboard, Leaf, LogOut, Pencil, Plus, Settings2, ShieldCheck, Smartphone, Trash2, WifiOff, X } from 'lucide-react'
import type { Session } from '@supabase/supabase-js'
import { Button } from './components/ui/button'
import { deleteReading, exportCsv, fastingLabel, listReadings, localDateInput, saveReading, supabase, type Reading, type Unit } from './lib/data'

type Page = 'home' | 'history' | 'settings'
const dateLabel = (date: string) => new Date(date).toLocaleDateString('es-MX',{day:'numeric',month:'short',year:'numeric'})
const timeLabel = (date: string) => new Date(date).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})

export default function App() {
  const [session,setSession] = useState<Session|null>(null)
  const [authReady,setAuthReady] = useState(!supabase)
  const [authError,setAuthError] = useState(readAuthRedirectError)
  const [page,setPage] = useState<Page>('home')
  const [readings,setReadings] = useState<Reading[]>([])
  const [loading,setLoading] = useState(true)
  const [loadError,setLoadError] = useState('')
  const [notice,setNotice] = useState('')
  const [online,setOnline] = useState(navigator.onLine)
  const [editing,setEditing] = useState<Reading|null>(null)
  const [removing,setRemoving] = useState<Reading|null>(null)
  const [deleting,setDeleting] = useState(false)
  const [deleteError,setDeleteError] = useState('')
  const [unit,setUnit] = useState<Unit>(()=>localStorage.getItem('salud100.unit')==='mmol/L'?'mmol/L':'mg/dL')
  const [filter,setFilter] = useState('all')
  const [period,setPeriod] = useState('all')
  const [chartDays,setChartDays] = useState(7)
  const mainRef = useRef<HTMLElement>(null)
  useEffect(()=>{
    if(!supabase) return
    supabase.auth.getSession().then(({data,error})=>{if(error)setAuthError(authErrorMessage(error));setSession(data.session);setAuthReady(true)}).catch(()=>{setAuthError(authErrorMessage(null));setAuthReady(true)})
    const {data:{subscription}} = supabase.auth.onAuthStateChange((_event,s)=>{setSession(s);setAuthReady(true);if(!s)setReadings([])})
    return ()=>subscription.unsubscribe()
  },[])
  useEffect(()=>{ const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener('online',on);window.addEventListener('offline',off);return ()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off)} },[])
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5500);return ()=>clearTimeout(timer)},[notice])
  async function refresh() {setLoading(true);setLoadError('');try{setReadings((await listReadings()).sort((a,b)=>Date.parse(b.measured_at)-Date.parse(a.measured_at)))}catch(e){setLoadError(e instanceof Error?e.message:'No pudimos cargar tus datos.')}finally{setLoading(false)}}
  useEffect(()=>{if(authReady && (!supabase || session)) void refresh()},[authReady,session?.user.id])
  const navigate = (next: Page) => {setPage(next);window.scrollTo({top:0,behavior:'smooth'})}
  const latest = readings[0]
  const week = readings.filter(r=>Date.parse(r.measured_at)>=Date.now()-7*86400000 && r.unit===unit)
  const average = week.length ? (week.reduce((sum,r)=>sum+r.value,0)/week.length).toFixed(unit==='mg/dL'?0:1) : '—'
  const visible = readings.filter(r=>(filter==='all'||(filter==='yes'?r.fasting===true:filter==='no'?r.fasting===false:r.fasting===null)) && (period==='all'||Date.parse(r.measured_at)>=Date.now()-Number(period)*86400000))
  async function saved(reading: Reading) {setReadings(prev=>[reading,...prev.filter(r=>r.id!==reading.id)].sort((a,b)=>Date.parse(b.measured_at)-Date.parse(a.measured_at)));setEditing(null);setNotice('Medición guardada. Un pequeño paso para cuidarte.')}
  async function remove() {if(!removing)return;setDeleting(true);setDeleteError('');try{await deleteReading(removing.id);setReadings(prev=>prev.filter(r=>r.id!==removing.id));setRemoving(null);setNotice('Medición eliminada.')}catch(e){setDeleteError(e instanceof Error?e.message:'No se pudo eliminar.')}finally{setDeleting(false)}}
  if(!authReady) return <div className="loading-screen"><Droplet/> Preparando tu espacio…</div>
  if(supabase && !session) return <AuthScreen initialError={authError} />
  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('home')}}><span className="brand-icon"><Droplet size={24} fill="currentColor"/></span>salud<span className="brand-number">100</span><span className="brand-dot">.</span></a><div className="sidebar-caption">TU ESPACIO DE BIENESTAR</div>
      <nav aria-label="Navegación principal">{([{id:'home',label:'Mi resumen',icon:LayoutDashboard},{id:'history',label:'Mis mediciones',icon:History},{id:'settings',label:'Ajustes',icon:Settings2}] as const).map(item=><button key={item.id} className={'nav-item '+(page===item.id?'active':'')} aria-current={page===item.id?'page':undefined} onClick={()=>navigate(item.id)}><item.icon size={20}/><span>{item.label}</span>{page===item.id&&<span className="nav-dot"/>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="care-card"><span className="care-icon"><Heart size={20}/></span><h3>Cada registro cuenta.</h3><p>Pequeños hábitos, más tranquilidad en tu día.</p><span className="care-leaf"><Leaf size={68}/></span></div><div className="profile"><div className="avatar">{session?.user.email?.[0].toUpperCase()||'T'}</div><div><strong>Mi espacio personal</strong><small>{supabase?'Cuenta conectada':'Guardado en este dispositivo'}</small></div><ShieldCheck size={18}/></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><span className="breadcrumb">Mi bienestar <ChevronRight size={14}/><strong>{page==='home'?'Resumen':page==='history'?'Mediciones':'Ajustes'}</strong></span><span className="topbar-right"><span className="status-dot"/>{supabase?'Cuenta personal':'Modo local'}<span className="tiny-avatar"><Heart size={16}/></span></span></header>
    <main ref={mainRef}>
      {!online&&<div className="info-banner"><WifiOff size={18}/>{supabase?'Sin conexión. Para guardar en tu cuenta necesitas internet.':'Sin conexión. Puedes seguir guardando en este dispositivo.'}</div>}
      {loadError&&<div className="error-banner" role="alert">{loadError}<Button variant="outline" onClick={refresh}>Reintentar</Button></div>}
      {page==='home'&&<>
        <div className="page-heading"><div><div className="eyebrow"><span/> UN DÍA A LA VEZ</div><h1>Tu glucosa, a tu ritmo<span>.</span></h1><p>Llevar tu registro es una forma de cuidarte. Hagámoslo fácil.</p></div><div className="today"><Clock3 size={16}/>{new Date().toLocaleDateString('es-MX',{day:'numeric',month:'long',year:'numeric'})}</div></div>
        <div className="dashboard-grid"><section className="card entry-card"><div className="section-heading"><div className="heading-icon"><Plus size={22}/></div><div><h2>Nueva medición</h2><p>Un momento para ti.</p></div><span className="small-tag">REGISTRO RÁPIDO</span></div><ReadingForm unit={unit} disabled={loading||!!loadError} onSaved={saved}/></section>
          <div className="summary-stack"><section className="latest-card"><div className="latest-top"><span><span className="live-dot"/> Tu última medición</span><Droplet size={23}/></div><div className="latest-value">{latest?latest.value:'—'}<span>{latest?.unit||unit}</span></div>{latest?<><span className="fasting-badge"><Coffee size={14}/>{fastingLabel(latest.fasting)}</span><div className="latest-bottom"><Clock3 size={15}/>{dateLabel(latest.measured_at)} · {timeLabel(latest.measured_at)}</div></>:<><p className="latest-empty">Aquí comienza tu registro.</p><div className="latest-bottom">Tu primera medición aparecerá aquí.</div></>}<div className="decor-ring ring-one"/><div className="decor-ring ring-two"/></section>
          <section className="card weekly-card"><div className="weekly-title"><span className="soft-icon"><Activity size={19}/></span><span>Esta semana</span><span className="muted">Últimos 7 días</span></div><div className="weekly-stats"><div><strong>{week.length}</strong><span>mediciones en {unit}</span></div><div><strong>{average}<small>{unit}</small></strong><span>promedio registrado</span></div></div></section>
          <div className="gentle-note"><span><Leaf size={23}/></span><p>Lo importante es la constancia.<br/><strong>Tu próximo registro también cuenta.</strong></p></div></div>
        </div>
        <section className="card chart-card"><div className="section-line"><div><h2>Tu recorrido</h2><p>Tus mediciones a lo largo del tiempo · {unit}</p></div><div className="segmented compact">{[7,30].map(n=><button key={n} className={chartDays===n?'selected':''} onClick={()=>setChartDays(n)}>{n} días</button>)}</div></div><Trend readings={readings.filter(r=>r.unit===unit&&Date.parse(r.measured_at)>=Date.now()-chartDays*86400000)} unit={unit}/></section>
        <section className="card history-card"><div className="section-line"><div><h2>Últimos registros</h2><p>Cada medición, en su lugar.</p></div><Button variant="ghost" onClick={()=>navigate('history')}>Ver historial <ArrowRight size={16}/></Button></div><ReadingList readings={readings.slice(0,5)} loading={loading} onEdit={setEditing} onDelete={r=>{setDeleteError('');setRemoving(r)}}/></section>
      </>}
      {page==='history'&&<><div className="page-heading"><div><div className="eyebrow">TU HISTORIA, PASO A PASO</div><h1>Mis mediciones<span>.</span></h1><p>Consulta, corrige o lleva tus registros contigo.</p></div><Button variant="outline" disabled={!visible.length} onClick={()=>exportCsv(visible)}><ArrowDownToLine size={17}/>Exportar CSV</Button></div><section className="card history-card"><div className="history-filters"><label>Momento<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos los registros</option><option value="yes">En ayunas</option><option value="no">Sin ayuno</option><option value="unknown">Sin indicar</option></select></label><label>Periodo<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">Todo el historial</option><option value="7">Últimos 7 días</option><option value="30">Últimos 30 días</option><option value="90">Últimos 90 días</option></select></label><span>{visible.length} registros</span></div><ReadingList readings={visible} loading={loading} onEdit={setEditing} onDelete={r=>{setDeleteError('');setRemoving(r)}}/></section></>}
      {page==='settings'&&<><div className="page-heading"><div><div className="eyebrow">A TU MANERA</div><h1>Tu espacio<span>.</span></h1><p>Los pequeños detalles que hacen todo más fácil.</p></div></div><div className="settings-grid"><section className="card settings-card"><span className="heading-icon"><Droplet size={22}/></span><h2>Unidad de tu glucómetro</h2><p>Elige la unidad que aparece en tu dispositivo. Los registros anteriores conservan su unidad original.</p><label>Unidad de nuevas mediciones<select value={unit} onChange={e=>{try{localStorage.setItem('salud100.unit',e.target.value);setUnit(e.target.value as Unit);setNotice('Unidad actualizada.')}catch{setNotice('No pudimos guardar la preferencia.')}}}><option>mg/dL</option><option>mmol/L</option></select></label></section><section className="card settings-card"><span className="heading-icon"><ShieldCheck size={22}/></span><h2>Tus datos</h2><p>{supabase?'Tus mediciones se guardan en tu cuenta personal. Necesitas conexión para consultarlas y modificarlas.':'Tus mediciones se guardan solo en este navegador. Exporta una copia para conservarlas: borrar los datos del navegador también borra este registro.'}</p><Button variant="outline" onClick={()=>exportCsv(readings)} disabled={!readings.length}><ArrowDownToLine size={17}/>Exportar mis mediciones</Button>{supabase&&<Button variant="ghost" onClick={async()=>{const {error}=await supabase!.auth.signOut();if(error)setNotice('No se pudo cerrar sesión. Intenta de nuevo.')}}><LogOut size={17}/>Cerrar sesión</Button>}</section><section className="card settings-card install-card"><span className="heading-icon"><Smartphone size={22}/></span><h2>Siempre a la mano</h2><p>Agrega Salud100 a la pantalla de inicio de tu celular.</p><div className="install-steps"><p><strong>En iPhone</strong>Abre en Safari → Compartir → Agregar a pantalla de inicio.</p><p><strong>En Android</strong>Abre el menú de Chrome → Instalar app o Agregar a pantalla de inicio.</p></div></section></div></>}
      <footer><span><Droplet size={14}/>salud100 · Hecho para cuidarte</span><span>Un registro personal, sin interpretaciones médicas.</span></footer>
    </main></div>
    {notice&&<div className="toast" role="status"><Check size={19}/>{notice}<button aria-label="Cerrar aviso" onClick={()=>setNotice('')}><X size={17}/></button></div>}
    {editing&&<Modal title="Editar medición" onClose={()=>setEditing(null)}><ReadingForm unit={editing.unit} reading={editing} onSaved={saved}/></Modal>}
    {removing&&<Modal title="¿Eliminar esta medición?" onClose={()=>{if(!deleting)setRemoving(null)}}><p className="delete-copy">Se eliminará el registro de <strong>{removing.value} {removing.unit}</strong> del {dateLabel(removing.measured_at)} a las {timeLabel(removing.measured_at)}. Esta acción no se puede deshacer.</p>{deleteError&&<p role="alert" className="form-error">{deleteError}</p>}<div className="modal-actions"><Button variant="outline" disabled={deleting} onClick={()=>setRemoving(null)}>Conservar</Button><Button variant="destructive" disabled={deleting} onClick={remove}>{deleting?'Eliminando…':'Eliminar medición'}</Button></div></Modal>}
  </div>
}

function ReadingForm({unit,reading,onSaved,disabled=false}:{unit:Unit;reading?:Reading;onSaved:(r:Reading)=>void;disabled?:boolean}) {
  const [value,setValue]=useState(reading?String(reading.value):'')
  const [fasting,setFasting]=useState<boolean|null>(reading?.fasting??null)
  const [note,setNote]=useState(reading?.note||'')
  const [customTime,setCustomTime]=useState(!!reading)
  const [date,setDate]=useState(localDateInput(reading?new Date(reading.measured_at):new Date()))
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState('')
  const inputRef=useRef<HTMLInputElement>(null)
  const inFlight=useRef(false)
  async function submit(e:FormEvent) {e.preventDefault();if(inFlight.current)return;setError('');const parsed=Number(value.replace(',','.'));if(!value.trim()||!Number.isFinite(parsed)||parsed<=0||parsed>=10000){setError('Escribe un valor numérico mayor que 0 y menor que 10000.');inputRef.current?.focus();return}const measured=customTime?new Date(date):new Date();if(!Number.isFinite(measured.getTime())||measured.getTime()>Date.now()+60000){setError('Elige una fecha y hora válida que no esté en el futuro.');return}const item:Reading={id:reading?.id||crypto.randomUUID(),value:parsed,unit,fasting,note:note.trim(),measured_at:measured.toISOString()};inFlight.current=true;setBusy(true);try{await saveReading(item);onSaved(item);if(!reading){setValue('');setFasting(null);setNote('');setCustomTime(false);setDate(localDateInput())}}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar. Revisa el espacio disponible en tu navegador.')}finally{setBusy(false);inFlight.current=false}}
  return <form onSubmit={submit} className="reading-form"><label className="field-label" htmlFor={reading?'edit-glucose':'glucose'}>¿Qué valor marcó tu glucómetro?</label><div className={'glucose-input '+(value?'has-value':'')}><Droplet size={25}/><input ref={inputRef} id={reading?'edit-glucose':'glucose'} aria-describedby="glucose-hint" type="text" inputMode="decimal" autoComplete="off" placeholder="000" value={value} onChange={e=>setValue(e.target.value)} disabled={busy||disabled}/><span>{unit}</span></div><p id="glucose-hint" className="input-hint">Escribe el número tal como aparece en tu dispositivo.</p>
    <fieldset disabled={busy||disabled}><legend>¿Estabas en ayunas?</legend><div className="segmented fasting-options">{([{value:true,label:'Sí, en ayunas',icon:Coffee},{value:false,label:'No',icon:Leaf},{value:null,label:'Sin indicar',icon:Clock3}] as const).map(option=><button type="button" key={option.label} aria-pressed={fasting===option.value} className={fasting===option.value?'selected':''} onClick={()=>setFasting(option.value)}><option.icon size={16}/>{option.label}</button>)}</div></fieldset>
    <div className="time-row"><Clock3 size={17}/><div><strong>{customTime?'Fecha y hora personalizadas':'Fecha y hora automáticas'}</strong><span>{customTime?'La medición se guardará con la fecha elegida.':'Se registran al guardar tu medición.'}</span></div><button type="button" disabled={busy} onClick={()=>{setCustomTime(reading?true:!customTime);if(!customTime)setDate(localDateInput())}}>{customTime&&!reading?'Usar ahora':'Cambiar'}</button></div>
    {customTime&&<label className="date-field">Fecha y hora de la medición<input aria-label="Fecha y hora de la medición" type="datetime-local" required value={date} max={localDateInput()} onChange={e=>setDate(e.target.value)} disabled={busy}/></label>}
    <details className="note-details" open={note?true:undefined}><summary><Plus size={15}/>Añadir una nota <span>(opcional)</span></summary><textarea aria-label="Nota" placeholder="Algo que quieras recordar…" maxLength={500} value={note} onChange={e=>setNote(e.target.value)} disabled={busy}/></details>
    {error&&<p className="form-error" role="alert">{error}</p>}<Button type="submit" className="save-button" disabled={busy||disabled}>{busy?'Guardando…':reading?'Guardar cambios':'Guardar medición'}{!busy&&<ArrowRight size={19}/>}</Button><div className="save-caption"><ShieldCheck size={13}/>{supabase?'En tu cuenta personal':'Guardado en este dispositivo'}</div>
  </form>
}

function ReadingList({readings,loading,onEdit,onDelete}:{readings:Reading[];loading:boolean;onEdit:(r:Reading)=>void;onDelete:(r:Reading)=>void}) {if(loading)return <div className="empty-state">Cargando tus mediciones…</div>;if(!readings.length)return <div className="empty-state"><span className="empty-icon"><Droplet size={26}/></span><strong>Aquí se escribe tu historia</strong><p>Tus mediciones aparecerán aquí cuando las guardes.<br/>Si elegiste filtros, prueba con otro periodo.</p></div>;return <div className="table-wrap"><table><thead><tr><th>FECHA Y HORA</th><th>GLUCOSA</th><th>MOMENTO</th><th>NOTA</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{readings.map(r=><tr key={r.id}><td><strong>{dateLabel(r.measured_at)}</strong><small>{timeLabel(r.measured_at)}</small></td><td><span className="table-value">{r.value}</span><span className="table-unit">{r.unit}</span></td><td><span className={'reading-badge '+(r.fasting===true?'fasting':'')}>{r.fasting===true&&<Coffee size={13}/>} {fastingLabel(r.fasting)}</span></td><td className="note-cell">{r.note||'—'}</td><td><div className="row-actions"><Button variant="ghost" size="icon" aria-label={`Editar medición de ${r.value}`} onClick={()=>onEdit(r)}><Pencil size={16}/></Button><Button variant="ghost" size="icon" aria-label={`Eliminar medición de ${r.value}`} onClick={()=>onDelete(r)}><Trash2 size={16}/></Button></div></td></tr>)}</tbody></table></div>}

function Trend({readings,unit}:{readings:Reading[];unit:Unit}) {if(readings.length<2)return <div className="chart-empty"><div className="chart-empty-lines"/><span className="empty-icon"><Activity size={25}/></span><strong>Un registro hoy, una historia mañana.</strong><p>Con al menos dos mediciones verás aquí tu recorrido.</p></div>;const sorted=[...readings].sort((a,b)=>Date.parse(a.measured_at)-Date.parse(b.measured_at));const values=sorted.map(r=>r.value);const min=Math.max(0,Math.min(...values)-10),max=Math.max(...values)+10;const start=Date.parse(sorted[0].measured_at),end=Date.parse(sorted.at(-1)!.measured_at);const points=sorted.map(r=>({x:55+(Date.parse(r.measured_at)-start)/(end-start||1)*880,y:155-(r.value-min)/(max-min)*125,r}));const path=points.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');return <div className="trend"><svg viewBox="0 0 970 195" role="img" aria-label={`Gráfica de ${readings.length} mediciones en ${unit}; valores disponibles en el historial`}><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#219782" stopOpacity=".15"/><stop offset="100%" stopColor="#219782" stopOpacity="0"/></linearGradient></defs>{[0,1,2].map(i=><g key={i}><line x1="55" x2="935" y1={30+i*62.5} y2={30+i*62.5} stroke="#e9efed" strokeDasharray="4 5"/><text x="5" y={35+i*62.5} fill="#85918c" fontSize="12">{(max-i*(max-min)/2).toFixed(unit==='mg/dL'?0:1)}</text></g>)}<path d={`${path} L ${points.at(-1)!.x} 160 L 55 160 Z`} fill="url(#chart-fill)"/><path d={path} fill="none" stroke="#168574" strokeWidth="3" strokeLinejoin="round"/>{points.map(p=><circle key={p.r.id} cx={p.x} cy={p.y} r="4" fill="#168574" stroke="white" strokeWidth="2"><title>{p.r.value} {unit} · {dateLabel(p.r.measured_at)} {timeLabel(p.r.measured_at)}</title></circle>)}<text x="55" y="187" fill="#85918c" fontSize="12">{dateLabel(sorted[0].measured_at)}</text><text x="935" y="187" textAnchor="end" fill="#85918c" fontSize="12">{dateLabel(sorted.at(-1)!.measured_at)}</text></svg></div>}

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) {const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}},[]);return <dialog ref={ref} className="modal" aria-labelledby="modal-title" onCancel={e=>{e.preventDefault();onClose()}}><div className="modal-heading"><h2 id="modal-title">{title}</h2><Button variant="ghost" size="icon" aria-label="Cerrar ventana" onClick={onClose}><X size={20}/></Button></div>{children}</dialog>}
